// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package db

import (
	"context"
)

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, slug, title, description, created_at
FROM boards
WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id int64) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getBoardBySlug = `-- name: GetBoardBySlug :one
SELECT id, slug, title, description, created_at
FROM boards
WHERE slug = $1
`

func (q *Queries) GetBoardBySlug(ctx context.Context, slug string) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardBySlug, slug)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, slug, title, description, created_at
FROM boards
ORDER BY slug ASC
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
