// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, parent_id, author_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, parent_id, author_id, body, score, created_at, updated_at, is_deleted, deleted_at
`

type CreateCommentParams struct {
	PostID   int64       `json:"post_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	AuthorID int64       `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return i, err
}

const getCommentThreadByPost = `-- name: GetCommentThreadByPost :many
WITH RECURSIVE thread AS (
    -- Anchor: top-level comments (parent_id IS NULL)
    SELECT
        c.id,
        c.post_id,
        c.parent_id,
        c.author_id,
        c.body,
        c.score,
        c.created_at,
        c.updated_at,
        c.is_deleted,
        (CASE WHEN c.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle,
        0::INT   AS depth,
        ARRAY[c.id] AS path
    FROM comments c
    JOIN users u ON u.id = c.author_id
    WHERE c.post_id = $1 AND c.parent_id IS NULL

    UNION ALL

    -- Recursive: child comments (strictly constrained to same post_id with depth ceiling)
    SELECT
        c.id,
        c.post_id,
        c.parent_id,
        c.author_id,
        c.body,
        c.score,
        c.created_at,
        c.updated_at,
        c.is_deleted,
        (CASE WHEN c.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle,
        t.depth + 1,
        t.path || c.id
    FROM comments c
    JOIN users u ON u.id = c.author_id
    JOIN thread t ON t.id = c.parent_id
    WHERE c.post_id = $1 AND t.depth < 15
)
SELECT id, post_id, parent_id, author_id, body, score,
       created_at, updated_at, is_deleted, author_handle, depth, path
FROM thread
ORDER BY path, created_at ASC
LIMIT $2
`

type GetCommentThreadByPostParams struct {
	PostID int64 `json:"post_id"`
	Limit  int32 `json:"limit"`
}

type GetCommentThreadByPostRow struct {
	ID           int64              `json:"id"`
	PostID       int64              `json:"post_id"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	AuthorID     int64              `json:"author_id"`
	Body         string             `json:"body"`
	Score        int32              `json:"score"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    bool               `json:"is_deleted"`
	AuthorHandle string             `json:"author_handle"`
	Depth        int32              `json:"depth"`
	Path         interface{}        `json:"path"`
}

// Recursive CTE that returns the comment tree for a post up to depth 15,
// ordered depth-first by (path, created_at).
func (q *Queries) GetCommentThreadByPost(ctx context.Context, arg GetCommentThreadByPostParams) ([]GetCommentThreadByPostRow, error) {
	rows, err := q.db.Query(ctx, getCommentThreadByPost, arg.PostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentThreadByPostRow{}
	for rows.Next() {
		var i GetCommentThreadByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
			&i.AuthorHandle,
			&i.Depth,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteComment = `-- name: HardDeleteComment :exec
DELETE FROM comments
WHERE id = $1 AND author_id = $2
`

type HardDeleteCommentParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) HardDeleteComment(ctx context.Context, arg HardDeleteCommentParams) error {
	_, err := q.db.Exec(ctx, hardDeleteComment, arg.ID, arg.AuthorID)
	return err
}

const hardDeleteCommentIfNoChildren = `-- name: HardDeleteCommentIfNoChildren :execrows
DELETE FROM comments
WHERE comments.id = $1 AND comments.author_id = $2
  AND NOT EXISTS (
      SELECT 1 FROM comments c WHERE c.parent_id = comments.id
  )
`

type HardDeleteCommentIfNoChildrenParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) HardDeleteCommentIfNoChildren(ctx context.Context, arg HardDeleteCommentIfNoChildrenParams) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteCommentIfNoChildren, arg.ID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasCommentChildren = `-- name: HasCommentChildren :one
SELECT EXISTS(
    SELECT 1 FROM comments WHERE parent_id = $1
)::BOOLEAN
`

func (q *Queries) HasCommentChildren(ctx context.Context, parentID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, hasCommentChildren, parentID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneTombstoneComments = `-- name: PruneTombstoneComments :exec
WITH RECURSIVE active_ancestors AS (
    SELECT parent_id, 1 AS depth
    FROM comments
    WHERE post_id = $1 AND is_deleted = FALSE AND parent_id IS NOT NULL
    UNION
    SELECT c.parent_id, a.depth + 1
    FROM comments c
    JOIN active_ancestors a ON c.id = a.parent_id
    WHERE c.post_id = $1 AND c.parent_id IS NOT NULL AND a.depth < 15
)
DELETE FROM comments
WHERE comments.post_id = $1
  AND comments.is_deleted = TRUE
  AND comments.id NOT IN (SELECT parent_id FROM active_ancestors)
`

func (q *Queries) PruneTombstoneComments(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, pruneTombstoneComments, postID)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET is_deleted = TRUE,
    deleted_at = now(),
    body = '[deleted]'
WHERE id = $1 AND author_id = $2
`

type SoftDeleteCommentParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) error {
	_, err := q.db.Exec(ctx, softDeleteComment, arg.ID, arg.AuthorID)
	return err
}
