// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, parent_id, author_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, parent_id, author_id, body, score, created_at, updated_at
`

type CreateCommentParams struct {
	PostID   int64       `json:"post_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	AuthorID int64       `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.PostID,
		arg.ParentID,
		arg.AuthorID,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.ParentID,
		&i.AuthorID,
		&i.Body,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentThreadByPost = `-- name: GetCommentThreadByPost :many
WITH RECURSIVE thread AS (
    -- Anchor: top-level comments (parent_id IS NULL)
    SELECT
        c.id,
        c.post_id,
        c.parent_id,
        c.author_id,
        c.body,
        c.score,
        c.created_at,
        c.updated_at,
        u.handle AS author_handle,
        0::INT   AS depth,
        ARRAY[c.id] AS path
    FROM comments c
    JOIN users u ON u.id = c.author_id
    WHERE c.post_id = $1 AND c.parent_id IS NULL

    UNION ALL

    -- Recursive: child comments (strictly constrained to same post_id with depth ceiling)
    SELECT
        c.id,
        c.post_id,
        c.parent_id,
        c.author_id,
        c.body,
        c.score,
        c.created_at,
        c.updated_at,
        u.handle AS author_handle,
        t.depth + 1,
        t.path || c.id
    FROM comments c
    JOIN users u ON u.id = c.author_id
    JOIN thread t ON t.id = c.parent_id
    WHERE c.post_id = $1 AND t.depth < 15
)
SELECT id, post_id, parent_id, author_id, body, score,
       created_at, updated_at, author_handle, depth, path
FROM thread
ORDER BY path, created_at ASC
LIMIT $2
`

type GetCommentThreadByPostParams struct {
	PostID int64 `json:"post_id"`
	Limit  int32 `json:"limit"`
}

type GetCommentThreadByPostRow struct {
	ID           int64              `json:"id"`
	PostID       int64              `json:"post_id"`
	ParentID     pgtype.Int8        `json:"parent_id"`
	AuthorID     int64              `json:"author_id"`
	Body         string             `json:"body"`
	Score        int32              `json:"score"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	AuthorHandle string             `json:"author_handle"`
	Depth        int32              `json:"depth"`
	Path         interface{}        `json:"path"`
}

// Recursive CTE that returns the comment tree for a post up to depth 15,
// ordered depth-first by (path, created_at).
func (q *Queries) GetCommentThreadByPost(ctx context.Context, arg GetCommentThreadByPostParams) ([]GetCommentThreadByPostRow, error) {
	rows, err := q.db.Query(ctx, getCommentThreadByPost, arg.PostID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentThreadByPostRow{}
	for rows.Next() {
		var i GetCommentThreadByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.ParentID,
			&i.AuthorID,
			&i.Body,
			&i.Score,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorHandle,
			&i.Depth,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
