// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID          int64              `json:"id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Comment struct {
	ID        int64              `json:"id"`
	PostID    int64              `json:"post_id"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	AuthorID  int64              `json:"author_id"`
	Body      string             `json:"body"`
	Score     int32              `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsDeleted bool               `json:"is_deleted"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type CommentVote struct {
	UserID    int64              `json:"user_id"`
	CommentID int64              `json:"comment_id"`
	Direction int16              `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	ActorID   int64              `json:"actor_id"`
	PostID    int64              `json:"post_id"`
	CommentID pgtype.Int8        `json:"comment_id"`
	Type      string             `json:"type"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID           int64              `json:"id"`
	BoardID      int64              `json:"board_id"`
	AuthorID     int64              `json:"author_id"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Url          string             `json:"url"`
	Score        int32              `json:"score"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    bool               `json:"is_deleted"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	Category     string             `json:"category"`
	HotScore     float64            `json:"hot_score"`
}

type PostVote struct {
	UserID    int64              `json:"user_id"`
	PostID    int64              `json:"post_id"`
	Direction int16              `json:"direction"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int64              `json:"id"`
	PubkeySha256  string             `json:"pubkey_sha256"`
	Handle        string             `json:"handle"`
	Bio           string             `json:"bio"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PostKarma     int32              `json:"post_karma"`
	CommentKarma  int32              `json:"comment_karma"`
	LastCommentAt pgtype.Timestamptz `json:"last_comment_at"`
}
