// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, actor_id, post_id, comment_id, type)
VALUES ($1, $2, $3, $4, $5)
`

type CreateNotificationParams struct {
	UserID    int64       `json:"user_id"`
	ActorID   int64       `json:"actor_id"`
	PostID    int64       `json:"post_id"`
	CommentID pgtype.Int8 `json:"comment_id"`
	Type      string      `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.ActorID,
		arg.PostID,
		arg.CommentID,
		arg.Type,
	)
	return err
}

const getUnreadNotificationCount = `-- name: GetUnreadNotificationCount :one
SELECT COUNT(*)::BIGINT
FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) GetUnreadNotificationCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadNotificationCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listNotificationsKeyset = `-- name: ListNotificationsKeyset :many
SELECT n.id, n.user_id, n.actor_id, n.post_id, n.comment_id, n.type, n.is_read, n.created_at,
       u.handle AS actor_handle,
       p.title  AS post_title,
       COALESCE(c.body, '[deleted]') AS comment_snippet
FROM notifications n
JOIN users u ON u.id = n.actor_id
JOIN posts p ON p.id = n.post_id
LEFT JOIN comments c ON c.id = n.comment_id
WHERE n.user_id = $1
  AND (
      $3::TIMESTAMPTZ IS NULL
      OR (n.created_at < $3::TIMESTAMPTZ)
      OR (n.created_at = $3::TIMESTAMPTZ AND n.id < $4::BIGINT)
  )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $2
`

type ListNotificationsKeysetParams struct {
	UserID          int64              `json:"user_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.Int8        `json:"cursor_id"`
}

type ListNotificationsKeysetRow struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	ActorID        int64              `json:"actor_id"`
	PostID         int64              `json:"post_id"`
	CommentID      pgtype.Int8        `json:"comment_id"`
	Type           string             `json:"type"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorHandle    string             `json:"actor_handle"`
	PostTitle      string             `json:"post_title"`
	CommentSnippet string             `json:"comment_snippet"`
}

func (q *Queries) ListNotificationsKeyset(ctx context.Context, arg ListNotificationsKeysetParams) ([]ListNotificationsKeysetRow, error) {
	rows, err := q.db.Query(ctx, listNotificationsKeyset,
		arg.UserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsKeysetRow{}
	for rows.Next() {
		var i ListNotificationsKeysetRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.PostID,
			&i.CommentID,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorHandle,
			&i.PostTitle,
			&i.CommentSnippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationAsReadByID = `-- name: MarkNotificationAsReadByID :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) MarkNotificationAsReadByID(ctx context.Context, arg MarkNotificationAsReadByIDParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsReadByID, arg.ID, arg.UserID)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, markNotificationsRead, userID)
	return err
}
