// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (board_id, author_id, title, body, url, category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, board_id, author_id, title, body, url, score, comment_count, created_at, updated_at, is_deleted, deleted_at, category
`

type CreatePostParams struct {
	BoardID  int64  `json:"board_id"`
	AuthorID int64  `json:"author_id"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	Url      string `json:"url"`
	Category string `json:"category"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.BoardID,
		arg.AuthorID,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Category,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Score,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.Category,
	)
	return i, err
}

const decrementPostCommentCount = `-- name: DecrementPostCommentCount :exec
UPDATE posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = $1
`

func (q *Queries) DecrementPostCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostCommentCount, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id,
    p.board_id,
    p.author_id,
    p.title,
    p.body,
    p.url,
    p.score,
    p.comment_count,
    p.created_at,
    p.updated_at,
    p.is_deleted,
    p.category,
    (CASE WHEN p.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle,
    b.slug   AS board_slug
FROM posts p
JOIN users  u ON u.id = p.author_id
JOIN boards b ON b.id = p.board_id
WHERE p.id = $1
`

type GetPostByIDRow struct {
	ID           int64              `json:"id"`
	BoardID      int64              `json:"board_id"`
	AuthorID     int64              `json:"author_id"`
	Title        string             `json:"title"`
	Body         string             `json:"body"`
	Url          string             `json:"url"`
	Score        int32              `json:"score"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    bool               `json:"is_deleted"`
	Category     string             `json:"category"`
	AuthorHandle string             `json:"author_handle"`
	BoardSlug    string             `json:"board_slug"`
}

func (q *Queries) GetPostByID(ctx context.Context, id int64) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.AuthorID,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Score,
		&i.CommentCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.Category,
		&i.AuthorHandle,
		&i.BoardSlug,
	)
	return i, err
}

const hardDeletePost = `-- name: HardDeletePost :exec
DELETE FROM posts
WHERE id = $1 AND author_id = $2
`

type HardDeletePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) HardDeletePost(ctx context.Context, arg HardDeletePostParams) error {
	_, err := q.db.Exec(ctx, hardDeletePost, arg.ID, arg.AuthorID)
	return err
}

const hasPostComments = `-- name: HasPostComments :one
SELECT EXISTS(
    SELECT 1 FROM comments WHERE post_id = $1 AND is_deleted = FALSE
)::BOOLEAN
`

func (q *Queries) HasPostComments(ctx context.Context, postID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostComments, postID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts SET comment_count = comment_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostCommentCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostCommentCount, id)
	return err
}

const listPostsByBoardHot = `-- name: ListPostsByBoardHot :many
SELECT
    p.id,
    p.board_id,
    p.author_id,
    p.title,
    p.url,
    p.score,
    p.comment_count,
    p.created_at,
    p.is_deleted,
    p.category,
    (CASE WHEN p.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.board_id = $1
  AND (p.is_deleted = FALSE OR p.comment_count > 0)
  AND ($4::TEXT = '' OR p.category = $4)
ORDER BY (
    (p.score + 1)::FLOAT / POWER(GREATEST(1.0, EXTRACT(EPOCH FROM (now() - p.created_at))/3600.0 + 2.0), 1.5)
) DESC, p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByBoardHotParams struct {
	BoardID  int64  `json:"board_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
	Category string `json:"category"`
}

type ListPostsByBoardHotRow struct {
	ID           int64              `json:"id"`
	BoardID      int64              `json:"board_id"`
	AuthorID     int64              `json:"author_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Score        int32              `json:"score"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsDeleted    bool               `json:"is_deleted"`
	Category     string             `json:"category"`
	AuthorHandle string             `json:"author_handle"`
}

func (q *Queries) ListPostsByBoardHot(ctx context.Context, arg ListPostsByBoardHotParams) ([]ListPostsByBoardHotRow, error) {
	rows, err := q.db.Query(ctx, listPostsByBoardHot,
		arg.BoardID,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByBoardHotRow{}
	for rows.Next() {
		var i ListPostsByBoardHotRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Url,
			&i.Score,
			&i.CommentCount,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.Category,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByBoardNew = `-- name: ListPostsByBoardNew :many
SELECT
    p.id,
    p.board_id,
    p.author_id,
    p.title,
    p.url,
    p.score,
    p.comment_count,
    p.created_at,
    p.is_deleted,
    p.category,
    (CASE WHEN p.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.board_id = $1
  AND (p.is_deleted = FALSE OR p.comment_count > 0)
  AND ($4::TEXT = '' OR p.category = $4)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByBoardNewParams struct {
	BoardID  int64  `json:"board_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
	Category string `json:"category"`
}

type ListPostsByBoardNewRow struct {
	ID           int64              `json:"id"`
	BoardID      int64              `json:"board_id"`
	AuthorID     int64              `json:"author_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Score        int32              `json:"score"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsDeleted    bool               `json:"is_deleted"`
	Category     string             `json:"category"`
	AuthorHandle string             `json:"author_handle"`
}

func (q *Queries) ListPostsByBoardNew(ctx context.Context, arg ListPostsByBoardNewParams) ([]ListPostsByBoardNewRow, error) {
	rows, err := q.db.Query(ctx, listPostsByBoardNew,
		arg.BoardID,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByBoardNewRow{}
	for rows.Next() {
		var i ListPostsByBoardNewRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Url,
			&i.Score,
			&i.CommentCount,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.Category,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByBoardTop = `-- name: ListPostsByBoardTop :many
SELECT
    p.id,
    p.board_id,
    p.author_id,
    p.title,
    p.url,
    p.score,
    p.comment_count,
    p.created_at,
    p.is_deleted,
    p.category,
    (CASE WHEN p.is_deleted THEN '[deleted]' ELSE u.handle END)::TEXT AS author_handle
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.board_id = $1
  AND (p.is_deleted = FALSE OR p.comment_count > 0)
  AND ($4::TEXT = '' OR p.category = $4)
ORDER BY p.score DESC, p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByBoardTopParams struct {
	BoardID  int64  `json:"board_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
	Category string `json:"category"`
}

type ListPostsByBoardTopRow struct {
	ID           int64              `json:"id"`
	BoardID      int64              `json:"board_id"`
	AuthorID     int64              `json:"author_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Score        int32              `json:"score"`
	CommentCount int32              `json:"comment_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsDeleted    bool               `json:"is_deleted"`
	Category     string             `json:"category"`
	AuthorHandle string             `json:"author_handle"`
}

func (q *Queries) ListPostsByBoardTop(ctx context.Context, arg ListPostsByBoardTopParams) ([]ListPostsByBoardTopRow, error) {
	rows, err := q.db.Query(ctx, listPostsByBoardTop,
		arg.BoardID,
		arg.Limit,
		arg.Offset,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByBoardTopRow{}
	for rows.Next() {
		var i ListPostsByBoardTopRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.AuthorID,
			&i.Title,
			&i.Url,
			&i.Score,
			&i.CommentCount,
			&i.CreatedAt,
			&i.IsDeleted,
			&i.Category,
			&i.AuthorHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAllEmptyDeletedPosts = `-- name: PruneAllEmptyDeletedPosts :exec
DELETE FROM posts
WHERE is_deleted = TRUE
  AND (
      comment_count = 0
      OR NOT EXISTS (
          SELECT 1 FROM comments WHERE comments.post_id = posts.id AND comments.is_deleted = FALSE
      )
  )
`

func (q *Queries) PruneAllEmptyDeletedPosts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAllEmptyDeletedPosts)
	return err
}

const pruneDeletedPostIfEmpty = `-- name: PruneDeletedPostIfEmpty :exec
DELETE FROM posts
WHERE posts.id = $1
  AND posts.is_deleted = TRUE
  AND (
      posts.comment_count = 0
      OR NOT EXISTS (
          SELECT 1 FROM comments WHERE comments.post_id = posts.id AND comments.is_deleted = FALSE
      )
  )
`

func (q *Queries) PruneDeletedPostIfEmpty(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, pruneDeletedPostIfEmpty, id)
	return err
}

const recalculatePostCommentCount = `-- name: RecalculatePostCommentCount :exec
UPDATE posts
SET comment_count = (
    SELECT COUNT(*)::INT FROM comments WHERE post_id = $1 AND is_deleted = FALSE
)
WHERE id = $1
`

func (q *Queries) RecalculatePostCommentCount(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, recalculatePostCommentCount, postID)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts
SET is_deleted = TRUE,
    deleted_at = now(),
    title = '[deleted]',
    body = '',
    url = ''
WHERE id = $1 AND author_id = $2
`

type SoftDeletePostParams struct {
	ID       int64 `json:"id"`
	AuthorID int64 `json:"author_id"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.AuthorID)
	return err
}
