// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DecrementPostCommentCount(ctx context.Context, id int64) error
	DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) error
	DeletePostVote(ctx context.Context, arg DeletePostVoteParams) error
	GetBoardByID(ctx context.Context, id int64) (Board, error)
	GetBoardBySlug(ctx context.Context, slug string) (Board, error)
	// Recursive CTE that returns the comment tree for a post up to depth 15,
	// ordered depth-first by (path, created_at).
	GetCommentThreadByPost(ctx context.Context, arg GetCommentThreadByPostParams) ([]GetCommentThreadByPostRow, error)
	GetCommentVoteByUser(ctx context.Context, arg GetCommentVoteByUserParams) (CommentVote, error)
	GetPostByID(ctx context.Context, id int64) (GetPostByIDRow, error)
	GetPostVoteByUser(ctx context.Context, arg GetPostVoteByUserParams) (PostVote, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPubkey(ctx context.Context, pubkeySha256 string) (User, error)
	IncrementPostCommentCount(ctx context.Context, id int64) error
	ListBoards(ctx context.Context) ([]Board, error)
	ListPostsByBoardNew(ctx context.Context, arg ListPostsByBoardNewParams) ([]ListPostsByBoardNewRow, error)
	ListPostsByBoardTop(ctx context.Context, arg ListPostsByBoardTopParams) ([]ListPostsByBoardTopRow, error)
	RecalculateCommentScore(ctx context.Context, commentID int64) error
	RecalculatePostScore(ctx context.Context, postID int64) error
	UpdateUserBio(ctx context.Context, arg UpdateUserBioParams) (User, error)
	UpdateUserHandle(ctx context.Context, arg UpdateUserHandleParams) (User, error)
	UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) error
	UpsertPostVote(ctx context.Context, arg UpsertPostVoteParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
