// Code generated by sqlc. DO NOT EDIT.
// This is a stub file. Run `make sqlc` to regenerate.
package db

import "context"

// GetUserByPubkey retrieves a user by their SSH public key fingerprint.
func (q *Queries) GetUserByPubkey(ctx context.Context, pubkeySha256 string) (User, error) {
	row := q.db.QueryRow(ctx,
		`SELECT id, pubkey_sha256, handle, bio, created_at, updated_at FROM users WHERE pubkey_sha256 = $1`,
		pubkeySha256,
	)
	var u User
	err := row.Scan(&u.ID, &u.PubkeySha256, &u.Handle, &u.Bio, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

// UpsertUser creates a new user or updates the timestamp for an existing one.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx,
		`INSERT INTO users (pubkey_sha256, handle) VALUES ($1, $2)
		ON CONFLICT (pubkey_sha256) DO UPDATE SET updated_at = now()
		RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at`,
		arg.PubkeySha256, arg.Handle,
	)
	var u User
	err := row.Scan(&u.ID, &u.PubkeySha256, &u.Handle, &u.Bio, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

// ListBoards returns all boards ordered by slug.
func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx,
		`SELECT id, slug, title, description, created_at FROM boards ORDER BY slug ASC`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var boards []Board
	for rows.Next() {
		var b Board
		if err := rows.Scan(&b.ID, &b.Slug, &b.Title, &b.Description, &b.CreatedAt); err != nil {
			return nil, err
		}
		boards = append(boards, b)
	}
	if boards == nil {
		boards = []Board{}
	}
	return boards, rows.Err()
}

// ListPostsByBoardNew returns posts for a board sorted by newest first.
func (q *Queries) ListPostsByBoardNew(ctx context.Context, arg ListPostsByBoardNewParams) ([]ListPostsByBoardNewRow, error) {
	rows, err := q.db.Query(ctx,
		`SELECT p.id, p.board_id, p.author_id, p.title, p.url, p.score, p.comment_count, p.created_at, u.handle AS author_handle
		FROM posts p JOIN users u ON u.id = p.author_id
		WHERE p.board_id = $1 ORDER BY p.created_at DESC LIMIT $2 OFFSET $3`,
		arg.BoardID, arg.Limit, arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var posts []ListPostsByBoardNewRow
	for rows.Next() {
		var p ListPostsByBoardNewRow
		if err := rows.Scan(&p.ID, &p.BoardID, &p.AuthorID, &p.Title, &p.URL, &p.Score, &p.CommentCount, &p.CreatedAt, &p.AuthorHandle); err != nil {
			return nil, err
		}
		posts = append(posts, p)
	}
	if posts == nil {
		posts = []ListPostsByBoardNewRow{}
	}
	return posts, rows.Err()
}
