// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, pubkey_sha256, handle, bio, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPubkey = `-- name: GetUserByPubkey :one
SELECT id, pubkey_sha256, handle, bio, created_at, updated_at
FROM users
WHERE pubkey_sha256 = $1
`

func (q *Queries) GetUserByPubkey(ctx context.Context, pubkeySha256 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPubkey, pubkeySha256)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserBio = `-- name: UpdateUserBio :one
UPDATE users
SET bio = $2, updated_at = now()
WHERE id = $1
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at
`

type UpdateUserBioParams struct {
	ID  int64  `json:"id"`
	Bio string `json:"bio"`
}

func (q *Queries) UpdateUserBio(ctx context.Context, arg UpdateUserBioParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserBio, arg.ID, arg.Bio)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserHandle = `-- name: UpdateUserHandle :one
UPDATE users
SET handle = $2, updated_at = now()
WHERE id = $1
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at
`

type UpdateUserHandleParams struct {
	ID     int64  `json:"id"`
	Handle string `json:"handle"`
}

func (q *Queries) UpdateUserHandle(ctx context.Context, arg UpdateUserHandleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserHandle, arg.ID, arg.Handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (pubkey_sha256, handle)
VALUES ($1, $2)
ON CONFLICT (pubkey_sha256)
DO UPDATE SET updated_at = now()
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at
`

type UpsertUserParams struct {
	PubkeySha256 string `json:"pubkey_sha256"`
	Handle       string `json:"handle"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.PubkeySha256, arg.Handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
