// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const adjustUserCommentKarma = `-- name: AdjustUserCommentKarma :exec
UPDATE users
SET comment_karma = comment_karma + $2, updated_at = now()
WHERE id = $1
`

type AdjustUserCommentKarmaParams struct {
	ID           int64 `json:"id"`
	CommentKarma int32 `json:"comment_karma"`
}

func (q *Queries) AdjustUserCommentKarma(ctx context.Context, arg AdjustUserCommentKarmaParams) error {
	_, err := q.db.Exec(ctx, adjustUserCommentKarma, arg.ID, arg.CommentKarma)
	return err
}

const adjustUserPostKarma = `-- name: AdjustUserPostKarma :exec
UPDATE users
SET post_karma = post_karma + $2, updated_at = now()
WHERE id = $1
`

type AdjustUserPostKarmaParams struct {
	ID        int64 `json:"id"`
	PostKarma int32 `json:"post_karma"`
}

func (q *Queries) AdjustUserPostKarma(ctx context.Context, arg AdjustUserPostKarmaParams) error {
	_, err := q.db.Exec(ctx, adjustUserPostKarma, arg.ID, arg.PostKarma)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}

const getUserByPubkey = `-- name: GetUserByPubkey :one
SELECT id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
FROM users
WHERE pubkey_sha256 = $1
`

func (q *Queries) GetUserByPubkey(ctx context.Context, pubkeySha256 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPubkey, pubkeySha256)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}

const getUserProfileByHandle = `-- name: GetUserProfileByHandle :one
SELECT id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
FROM users
WHERE handle = $1
`

func (q *Queries) GetUserProfileByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRow(ctx, getUserProfileByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}

const updateUserBio = `-- name: UpdateUserBio :one
UPDATE users
SET bio = $2, updated_at = now()
WHERE id = $1
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
`

type UpdateUserBioParams struct {
	ID  int64  `json:"id"`
	Bio string `json:"bio"`
}

func (q *Queries) UpdateUserBio(ctx context.Context, arg UpdateUserBioParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserBio, arg.ID, arg.Bio)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}

const updateUserHandle = `-- name: UpdateUserHandle :one
UPDATE users
SET handle = $2, updated_at = now()
WHERE id = $1
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
`

type UpdateUserHandleParams struct {
	ID     int64  `json:"id"`
	Handle string `json:"handle"`
}

func (q *Queries) UpdateUserHandle(ctx context.Context, arg UpdateUserHandleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserHandle, arg.ID, arg.Handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}

const updateUserLastCommentAt = `-- name: UpdateUserLastCommentAt :exec
UPDATE users
SET last_comment_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastCommentAt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastCommentAt, id)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (pubkey_sha256, handle)
VALUES ($1, $2)
ON CONFLICT (pubkey_sha256)
DO UPDATE SET updated_at = now()
RETURNING id, pubkey_sha256, handle, bio, created_at, updated_at, post_karma, comment_karma, last_comment_at
`

type UpsertUserParams struct {
	PubkeySha256 string `json:"pubkey_sha256"`
	Handle       string `json:"handle"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.PubkeySha256, arg.Handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PubkeySha256,
		&i.Handle,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PostKarma,
		&i.CommentKarma,
		&i.LastCommentAt,
	)
	return i, err
}
