// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package db

import (
	"context"
)

const deleteCommentVote = `-- name: DeleteCommentVote :exec
DELETE FROM comment_votes WHERE user_id = $1 AND comment_id = $2
`

type DeleteCommentVoteParams struct {
	UserID    int64 `json:"user_id"`
	CommentID int64 `json:"comment_id"`
}

func (q *Queries) DeleteCommentVote(ctx context.Context, arg DeleteCommentVoteParams) error {
	_, err := q.db.Exec(ctx, deleteCommentVote, arg.UserID, arg.CommentID)
	return err
}

const deletePostVote = `-- name: DeletePostVote :exec
DELETE FROM post_votes WHERE user_id = $1 AND post_id = $2
`

type DeletePostVoteParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) DeletePostVote(ctx context.Context, arg DeletePostVoteParams) error {
	_, err := q.db.Exec(ctx, deletePostVote, arg.UserID, arg.PostID)
	return err
}

const getCommentVoteByUser = `-- name: GetCommentVoteByUser :one
SELECT user_id, comment_id, direction, created_at
FROM comment_votes
WHERE user_id = $1 AND comment_id = $2
`

type GetCommentVoteByUserParams struct {
	UserID    int64 `json:"user_id"`
	CommentID int64 `json:"comment_id"`
}

func (q *Queries) GetCommentVoteByUser(ctx context.Context, arg GetCommentVoteByUserParams) (CommentVote, error) {
	row := q.db.QueryRow(ctx, getCommentVoteByUser, arg.UserID, arg.CommentID)
	var i CommentVote
	err := row.Scan(
		&i.UserID,
		&i.CommentID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const getPostVoteByUser = `-- name: GetPostVoteByUser :one
SELECT user_id, post_id, direction, created_at
FROM post_votes
WHERE user_id = $1 AND post_id = $2
`

type GetPostVoteByUserParams struct {
	UserID int64 `json:"user_id"`
	PostID int64 `json:"post_id"`
}

func (q *Queries) GetPostVoteByUser(ctx context.Context, arg GetPostVoteByUserParams) (PostVote, error) {
	row := q.db.QueryRow(ctx, getPostVoteByUser, arg.UserID, arg.PostID)
	var i PostVote
	err := row.Scan(
		&i.UserID,
		&i.PostID,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const recalculateCommentScore = `-- name: RecalculateCommentScore :exec
UPDATE comments
SET score = COALESCE((SELECT SUM(direction) FROM comment_votes WHERE comment_id = $1), 0)
WHERE id = $1
`

func (q *Queries) RecalculateCommentScore(ctx context.Context, commentID int64) error {
	_, err := q.db.Exec(ctx, recalculateCommentScore, commentID)
	return err
}

const recalculatePostScore = `-- name: RecalculatePostScore :exec
UPDATE posts
SET score = COALESCE((SELECT SUM(direction) FROM post_votes WHERE post_id = $1), 0)
WHERE id = $1
`

func (q *Queries) RecalculatePostScore(ctx context.Context, postID int64) error {
	_, err := q.db.Exec(ctx, recalculatePostScore, postID)
	return err
}

const upsertCommentVote = `-- name: UpsertCommentVote :exec
INSERT INTO comment_votes (user_id, comment_id, direction)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, comment_id)
DO UPDATE SET direction = EXCLUDED.direction, created_at = now()
`

type UpsertCommentVoteParams struct {
	UserID    int64 `json:"user_id"`
	CommentID int64 `json:"comment_id"`
	Direction int16 `json:"direction"`
}

func (q *Queries) UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) error {
	_, err := q.db.Exec(ctx, upsertCommentVote, arg.UserID, arg.CommentID, arg.Direction)
	return err
}

const upsertPostVote = `-- name: UpsertPostVote :exec
INSERT INTO post_votes (user_id, post_id, direction)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, post_id)
DO UPDATE SET direction = EXCLUDED.direction, created_at = now()
`

type UpsertPostVoteParams struct {
	UserID    int64 `json:"user_id"`
	PostID    int64 `json:"post_id"`
	Direction int16 `json:"direction"`
}

func (q *Queries) UpsertPostVote(ctx context.Context, arg UpsertPostVoteParams) error {
	_, err := q.db.Exec(ctx, upsertPostVote, arg.UserID, arg.PostID, arg.Direction)
	return err
}
